dataset: cityscapes
input_training: C:\Users\pso9kor\Datasets\cityscapes\leftImg8bit_trainvaltest\leftImg8bit\train
label_training: C:\Users\pso9kor\Datasets\cityscapes\gtFine_trainvaltest\gtFine\train
max_samples_training: 10000
input_validation: C:\Users\pso9kor\Datasets\cityscapes\leftImg8bit_trainvaltest\leftImg8bit\val
label_validation: C:\Users\pso9kor\Datasets\cityscapes\gtFine_trainvaltest\gtFine\val
max_samples_validation: 2000

# one_hot_palette_label: config\class.camvid.xml
one_hot_palette_label: config\labels.py

image_shape: [256, 256]
num_classes: 20
model: UNet
base_model: ResNet50_KA
bm_weights: 'imagenet'

epochs: 10
final_epoch: 40
batch_size: 8
valid_batch_size: 8
learning_rate: 1e-4
early_stopping_patience: 10
loss: self_balanced_focal_loss
optimizer: adam

checkpoint_freq: 5
output_dir: output

# model-weights
# weights: output\2023-06-22-08-58-26\checkpoints\best_weights.h5
weights: output\2023-06-22-08-58-26\weights\saved_model.pb


# for predict.py only
input_testing: C:\Users\pso9kor\Datasets\cityscapes\leftImg8bit_trainvaltest\leftImg8bit\test
label_testing: C:\Users\pso9kor\Datasets\cityscapes\gtFine_trainvaltest\gtFine\test
max_samples_testing: 5