# dataset
dataset: cityscapes
input_training: /kaggle/input/cityscapes-dataset/cityscapes_dataset/leftImg8bit/train
label_training: /kaggle/input/cityscapes-dataset/cityscapes_dataset/gtFine/train
max_samples_training: 10000
input_validation: /kaggle/input/cityscapes-dataset/cityscapes_dataset/leftImg8bit/val
label_validation: /kaggle/input/cityscapes-dataset/cityscapes_dataset/gtFine/val
max_samples_validation: 2000
label_file: config/labels.py
num_classes: 20

# loop training
loop_training: False

# model
image_shape: [256, 256]
model: DeepLabV3plus
base_model: Xception-DeepLab

# epochs
epochs: 50
final_epoch: 60
batch_size: 4
valid_batch_size: 8
shuffle: true
augment: true

# hyper parameters
random_seed: 101
learning_rate: 1e-4
lr_scheduler: polynomial_decay
early_stopping_patience: 10
loss: FocalHybridLoss
optimizer: AdamW

# output directory
output_dir: output

# model weights
weights: output\2023-06-26-15-15-41\weights\weights1.hdf5

# for predict.py only
input_testing: /kaggle/input/cityscapes-dataset/cityscapes_dataset/leftImg8bit/test
label_testing: /kaggle/input/cityscapes-dataset/cityscapes_dataset/gtFine/test
max_samples_testing: 5
