dataset: cityscapes
input_training: D:\Datasets\cityscapes\leftImg8bit_trainvaltest\leftImg8bit\train
label_training: D:\Datasets\cityscapes\gtFine_trainvaltest\gtFine\train
max_samples_training: 10000
input_validation: D:\Datasets\cityscapes\leftImg8bit_trainvaltest\leftImg8bit\val
label_validation: D:\Datasets\cityscapes\gtFine_trainvaltest\gtFine\val
max_samples_validation: 2000

# one-hot-palette-label: config\class.camvid.xml
one-hot-palette-label: config\labels.py

image_shape: [256, 256]
num_classes: 21
model: DeepLabV3
base_model: ResNet50

epochs: 40
batch_size: 8
valid_batch_size: 4
learning_rate: 1e-4
early_stopping_patience: 10
loss: miou_loss

checkpoint_freq: 5
output_dir: output
