dataset: cityscapes
input_training: D:\Datasets\cityscapes\leftImg8bit_trainvaltest\leftImg8bit\train
label_training: D:\Datasets\cityscapes\gtFine_trainvaltest\gtFine\train
max_samples_training: 10000
input_validation: D:\Datasets\cityscapes\leftImg8bit_trainvaltest\leftImg8bit\val
label_validation: D:\Datasets\cityscapes\gtFine_trainvaltest\gtFine\val
max_samples_validation: 2000

# one_hot_palette_label: config\class.camvid.xml
one_hot_palette_label: config\labels.py

image_shape: [256, 256]
num_classes: 21
model: UNet
base_model: ResNet50_KA
bm_weights: 'imagenet'

epochs: 30
batch_size: 8
valid_batch_size: 4
learning_rate: 1e-4
lr_warmup: False
early_stopping_patience: 10
loss: miou_loss

checkpoint_freq: 5
output_dir: output

# model-weights
weights: output\2023-06-11-02-14-55\checkpoints\best_weights.hdf5

# for predict.py only
input_testing: D:\Datasets\cityscapes\leftImg8bit_trainvaltest\leftImg8bit\test
label_testing: D:\Datasets\cityscapes\gtFine_trainvaltest\gtFine\test
max_samples_testing: 5