input_training: data\camvid\train\images
label_training: data\camvid\train\labels
max_samples_training: 10000
input_validation: data\camvid\valid\images
label_validation: data\camvid\valid\labels
max_samples_validation: 10000

image_shape: [256, 256]
one-hot-palette-label: data\camvid\class_32.xml

model: UNet

epochs: 20
batch_size: 4
valid_batch_size: 4
learning_rate: 1e-4
early_stopping_patience: 10

checkpoint_freq: 5
output_dir: output
