# dataset
dataset: cityscapes
input_training: D:\Datasets\cityscapes\leftImg8bit_trainvaltest\leftImg8bit\train
label_training: D:\Datasets\cityscapes\gtFine_trainvaltest\gtFine\train
max_samples_training: 10000
input_validation: D:\Datasets\cityscapes\leftImg8bit_trainvaltest\leftImg8bit\val
label_validation: D:\Datasets\cityscapes\gtFine_trainvaltest\gtFine\val
max_samples_validation: 2000
label_file: config\labels.py
num_classes: 20

# loop training
loop_training: False

# model
image_shape: [256, 256]
model: DeepLabV3plus
base_model: EfficientNetV2M

# epochs
epochs: 20
final_epoch: 40
batch_size: 4
valid_batch_size: 8
shuffle: true
augment: false

# hyper parameters
random_seed: 101
learning_rate: 1e-4
lr_scheduler: polynomial_decay
early_stopping_patience: 10
loss: FocalHybridLoss
optimizer: Adam

# output directory
output_dir: output

# model weights
weights: output\2023-06-26-15-15-41\weights\weights1.hdf5

# for predict.py only
input_testing: D:\Datasets\cityscapes\leftImg8bit_trainvaltest\leftImg8bit\test
label_testing: D:\Datasets\cityscapes\gtFine_trainvaltest\gtFine\test
max_samples_testing: 5